config/routes.rb
Rails.application.routes.draw do
  resources :sale_imports, only: %i(new create show)
  root 'sale_imports#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :sale
  belongs_to :product

  validates :price, :count, presence: true
  validates :product_id, uniqueness: { scope: :sale_id }
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  validates :name, :address, presence: true
  validates :address, uniqueness: { scope: :name }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :merchant
  validates :description, presence: true
  validates :description, uniqueness: { scope: :merchant_id }
end

app/models/purchaser.rb
class Purchaser < ApplicationRecord
  has_many :sales

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :purchaser
  belongs_to :sale_import
  has_many :items
end

app/models/sale_import.rb
class SaleImport < ApplicationRecord
  has_many :sales
  has_many :items, through: :sales

  def total_gross
    items.sum(&:price)
  end
end

app/models/sales_import_form_object.rb
class SalesImportFormObject
  include ActiveModel::Model
  attr_accessor :file

  validates :file, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sale_imports_controller.rb
class SaleImportsController < ApplicationController
  def new
    @form_object = SalesImportFormObject.new
  end

  def create
    @form_object = SalesImportFormObject.new(permitted_params)

    respond_to do |format|
      if @form_object.valid?
        @sale_import = SalesImporter::Importer.call(@form_object.file.read)
        format.html { redirect_to @sale_import }
      else
        format.html { render :new }
      end
    end
  end

  def show
    @sale_import = SaleImport.find(params[:id])
  end

  private

  def permitted_params
    params.fetch(:sales_import_form_object, {}).permit(:file)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sale_imports/create.html.erb
<h1>SalesImport#create</h1>

app/views/sale_imports/new.html.erb
<h1>SalesImport#new</h1>

<%= form_with(model: @form_object, url: sale_imports_path) do |form| %>
  <% if @form_object.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@form_object.errors.count, "error") %> prohibited this form_object from being saved:</h2>

      <ul>
        <% @form_object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :file %>
    <%= form.file_field :file %>
  </div>

  <div class="actions">
    <%= form.submit :import %>
  </div>
<% end %>

app/views/sale_imports/show.html.erb
Total Gross: <%= number_to_currency(@sale_import.total_gross, unit: "R$", separator: ",", delimiter: ".") %>